apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esf-backend-data-pvc
  namespace: esf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

