apiVersion: v1
kind: Secret
metadata:
  name: esf-secrets
  namespace: esf
type: Opaque
stringData:
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_REGION: "eu-west-1"
  S3_BUCKET: ""
  OPENSEARCH_ENDPOINT: ""
  OPENAI_API_KEY: ""
  AUTH0_DOMAIN: "dev-lzz2sk107uunqvja.us.auth0.com"
  AUTH0_AUDIENCE: "https://esf-dash-rag-api"
  FIRECRAWL_API_KEY: ""

